### ISSUE TITLE
Using Botex to implement LLM played experiment on Otree

### ISSUE THREAD

**Issue by Yizhi-91** [Yizhi-91/profile#1]
I am a new user of the Python package Botex. 

I have come across several issues that prevent me from running the experiment. I emailed Professor Joachim Gassen and received many good advice. Here I will put a summary of these issues and feedbacks.

Firstly, the setup of BOTEX_DB in the 'secrets.env' file is not working for me. I used the following code to circumvent this issue:

botex.run_single_bot(
    botex_db="botex.sqlite3",
    url="http://localhost:8000/InitializeParticipant/zltqkbs5"
)

This code set up the default database for the GPT data at "botex.sqlite3".

Second, I wanted to implement multiple GPT-played agents together with some human players and assign the human players to certain roles in the Otree experiment. 

The code to achieve this is:

sdict = botex.init_otree_session(
    config_name = "Analysing_Political_Corruption",
    npart = 7, # number of participants in the session, including bots and humans
    is_human=[True, True, False, False, False, False, False],
    botex_db = "botex.sqlite3",
    otree_server_url = "http://localhost:8000",
)

In this way, the first two players are human players and the last five players are GPT-played agents. 

The new issue that I wanted to ask is related to the Otree-rest-key problem. I am using a third-party server in China called yanzhonglab.com. I don't know how to set up the rest-key. Is Heroku easier to use in this regard? 

Can you help me with this?

Many thanks!

**Comment by Yizhi-91** [comment]
The error message is the following:

Request to "https://xu8uze.otree.yanzhonglab.com/api/sessions" failed with status code 403: HTTP Request Header otree-rest-key is incorrect

**Comment by Yizhi-91** [comment]
An update about this issue with rest-key. 

I found out that the rest-key is set up in the 'secrets.env' file and also in the settings file of the Otree folder. Now I have set both of them as '1234'. But the above error message still comes out. I don't know why this would happen. 

Many thanks

**Comment by joachim-gassen** [comment]
Hi there. Thank you for opening an issue but I meant you to open it in the [botex repository](https://github.com/joachim-gassen/botex/issues) so that other readers can see it. Can you maybe reraise your question there? Thanks!
